#LISTAS VS TUPLAS VS CONJUNTOS

#LISTAS: MUTABLES, ORDENADAS, INDEXING/SLICING , DUPLICAR ELEMENTOS
#TUPLAS: NO MUTABLES, ORDENADAS, INDEXING/SLICING, DUPLICAR ELEMENTOS
#CONJUNTOS: MUTABLES, NO ORDENADOS, NO INDEXING/NO SLICING, NO DOUPLICAR ELEMENTOS

